// Auto-generated reference map: CSS variable name → [lightRef, darkRef]
// Source: all_semantic_tokens.json from Figma export
export const SEMANTIC_REFS: Record<string, [string, string]> = {
  '--semantics-bg-subtle-primary-default': ['neutral-gray-50', 'neutral-default'],
  '--semantics-bg-subtle-primary-disabled': ['neutral-gray-100', 'neutral-gray-50'],
  '--semantics-bg-subtle-primary-hover': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-bg-subtle-primary-inversed-dynamic': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-bg-subtle-primary-inversed-static': ['neutral-gray-900', 'neutral-gray-50'],
  '--semantics-bg-subtle-primary-pressed': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-bg-subtle-secondary-default': ['neutral-default', 'neutral-gray-50'],
  '--semantics-bg-subtle-secondary-hover': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-bg-subtle-secondary-inversed-dynamic': ['neutral-inversed', 'neutral-inversed'],
  '--semantics-bg-subtle-secondary-inversed-static': ['neutral-inversed', 'neutral-default'],
  '--semantics-bg-subtle-secondary-pressed': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-bg-subtle-tertiary-default': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-bg-subtle-tertiary-hover': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-bg-subtle-tertiary-pressed': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-bg-brand-primary-default': ['brand-blue-50', 'brand-blue-50'],
  '--semantics-bg-brand-primary-hover': ['brand-blue-100', 'brand-blue-100'],
  '--semantics-bg-brand-primary-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-bg-brand-primary-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-bg-brand-primary-pressed': ['brand-blue-100', 'brand-blue-100'],
  '--semantics-bg-brand-secondary-default': ['brand-blue-100', 'brand-blue-100'],
  '--semantics-bg-brand-secondary-hover': ['brand-blue-200', 'brand-blue-200'],
  '--semantics-bg-brand-secondary-inversed-dynamic': ['brand-blue-800', 'brand-blue-800'],
  '--semantics-bg-brand-secondary-inversed-static': ['brand-blue-800', 'brand-blue-200'],
  '--semantics-bg-brand-secondary-pressed': ['brand-blue-200', 'brand-blue-200'],
  '--semantics-fill-subtle-primary-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-fill-subtle-primary-disabled': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-fill-subtle-primary-focus': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-fill-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-fill-subtle-primary-inversed-dynamic': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-fill-subtle-primary-inversed-static': ['neutral-gray-50', 'neutral-gray-900'],
  '--semantics-fill-subtle-primary-pressed': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-fill-subtle-secondary-default': ['neutral-default', 'neutral-gray-100'],
  '--semantics-fill-subtle-secondary-focus': ['neutral-default', 'neutral-gray-100'],
  '--semantics-fill-subtle-secondary-hover': ['neutral-gray-50', 'neutral-gray-200'],
  '--semantics-fill-subtle-secondary-inversed-dynamic': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-fill-subtle-secondary-inversed-static': ['neutral-gray-900', 'neutral-gray-100'],
  '--semantics-fill-subtle-secondary-pressed': ['neutral-gray-100', 'neutral-gray-300'],
  '--semantics-fill-subtle-tertiary-default': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-fill-subtle-tertiary-focus': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-fill-subtle-tertiary-hover': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-fill-subtle-tertiary-pressed': ['neutral-gray-200', 'neutral-gray-500'],
  '--semantics-fill-brand-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-fill-brand-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-fill-brand-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-fill-brand-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-fill-status-error-primary-default': ['error-red-500', 'error-red-500'],
  '--semantics-fill-status-error-primary-focus': ['error-red-500', 'error-red-500'],
  '--semantics-fill-status-error-primary-hover': ['error-red-600', 'error-red-600'],
  '--semantics-fill-status-error-primary-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-fill-status-error-secondary-default': ['error-red-500-10', 'error-red-500-25'],
  '--semantics-fill-status-error-secondary-disabled': ['error-red-500-15', 'error-red-500-25'],
  '--semantics-fill-status-error-secondary-focus': ['error-red-500-10', 'error-red-500-25'],
  '--semantics-fill-status-error-secondary-hover': ['error-red-500-25', 'error-red-500-50'],
  '--semantics-fill-status-error-secondary-pressed': ['error-red-500-25', 'error-red-500-50'],
  '--semantics-fill-status-info-primary-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-fill-status-info-primary-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-fill-status-info-primary-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-fill-status-info-primary-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-fill-status-info-secondary-default': ['brand-blue-500-10', 'brand-blue-500-25'],
  '--semantics-fill-status-info-secondary-disabled': ['brand-blue-500-15', 'brand-blue-500-25'],
  '--semantics-fill-status-info-secondary-focus': ['brand-blue-500-10', 'brand-blue-500-25'],
  '--semantics-fill-status-info-secondary-hover': ['brand-blue-500-25', 'brand-blue-500-50'],
  '--semantics-fill-status-info-secondary-pressed': ['brand-blue-500-25', 'brand-blue-500-50'],
  '--semantics-fill-status-subtle-primary-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-fill-status-subtle-primary-focus': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-fill-status-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-fill-status-subtle-primary-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-fill-status-subtle-primary-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-fill-status-subtle-primary-pressed': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-fill-status-subtle-secondary-default': [
    'neutral-black-shade-10',
    'neutral-black-shade-10',
  ],
  '--semantics-fill-status-subtle-secondary-disabled': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-fill-status-subtle-secondary-focus': [
    'neutral-black-shade-10',
    'neutral-black-shade-10',
  ],
  '--semantics-fill-status-subtle-secondary-hover': [
    'neutral-black-shade-15',
    'neutral-black-shade-15',
  ],
  '--semantics-fill-status-subtle-secondary-inversed-dynamic': [
    'neutral-50-tint-15',
    'neutral-50-tint-15',
  ],
  '--semantics-fill-status-subtle-secondary-inversed-static': [
    'neutral-50-tint-15',
    'neutral-black-shade-15',
  ],
  '--semantics-fill-status-subtle-secondary-pressed': [
    'neutral-black-shade-25',
    'neutral-black-shade-25',
  ],
  '--semantics-fill-status-success-primary-default': ['success-green-500', 'success-green-500'],
  '--semantics-fill-status-success-primary-focus': ['success-green-500', 'success-green-500'],
  '--semantics-fill-status-success-primary-hover': ['success-green-600', 'success-green-600'],
  '--semantics-fill-status-success-primary-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-fill-status-success-secondary-default': [
    'success-green-500-10',
    'success-green-500-25',
  ],
  '--semantics-fill-status-success-secondary-disabled': [
    'success-green-500-15',
    'success-green-500-25',
  ],
  '--semantics-fill-status-success-secondary-focus': [
    'success-green-500-10',
    'success-green-500-25',
  ],
  '--semantics-fill-status-success-secondary-hover': [
    'success-green-500-25',
    'success-green-500-50',
  ],
  '--semantics-fill-status-success-secondary-pressed': [
    'success-green-500-25',
    'success-green-500-50',
  ],
  '--semantics-fill-status-warning-primary-default': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-fill-status-warning-primary-focus': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-fill-status-warning-primary-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-fill-status-warning-primary-pressed': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-fill-status-warning-secondary-default': [
    'warning-orange-500-10',
    'warning-orange-500-25',
  ],
  '--semantics-fill-status-warning-secondary-disabled': [
    'warning-orange-500-15',
    'warning-orange-500-25',
  ],
  '--semantics-fill-status-warning-secondary-focus': [
    'warning-orange-500-10',
    'warning-orange-500-25',
  ],
  '--semantics-fill-status-warning-secondary-hover': [
    'warning-orange-500-25',
    'warning-orange-500-50',
  ],
  '--semantics-fill-status-warning-secondary-pressed': [
    'warning-orange-500-25',
    'warning-orange-500-50',
  ],
  '--semantics-text-subtle-primary-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-subtle-primary-disabled': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-text-subtle-primary-focus': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-text-subtle-primary-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-text-subtle-primary-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-text-subtle-primary-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-subtle-secondary-focus': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-text-subtle-secondary-hover': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-text-brand-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-brand-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-brand-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-brand-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-text-brand-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-text-brand-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-text-link-brand-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-link-brand-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-link-brand-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-text-link-brand-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-text-link-brand-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-text-link-status-error-default': ['error-red-500', 'error-red-500'],
  '--semantics-text-link-status-error-hover': ['error-red-600', 'error-red-600'],
  '--semantics-text-link-status-error-inversed-dynamic': ['error-red-900', 'error-red-900'],
  '--semantics-text-link-status-error-inversed-static': ['error-red-900', 'error-red-100'],
  '--semantics-text-link-status-error-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-text-link-status-info-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-link-status-info-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-link-status-info-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-text-link-status-info-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-text-link-status-info-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-text-link-status-success-default': ['success-green-500', 'success-green-500'],
  '--semantics-text-link-status-success-hover': ['success-green-600', 'success-green-600'],
  '--semantics-text-link-status-success-inversed-dynamic': [
    'success-green-900',
    'success-green-900',
  ],
  '--semantics-text-link-status-success-inversed-static': [
    'success-green-900',
    'success-green-100',
  ],
  '--semantics-text-link-status-success-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-text-link-status-warning-default': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-text-link-status-warning-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-text-link-status-warning-inversed-dynamic': [
    'warning-orange-900',
    'warning-orange-900',
  ],
  '--semantics-text-link-status-warning-inversed-static': [
    'warning-orange-900',
    'warning-orange-100',
  ],
  '--semantics-text-link-status-warning-pressed': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-text-link-subtle-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-link-subtle-disabled': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-text-link-subtle-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-text-link-subtle-inversed-dynamic': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-link-subtle-inversed-static': ['neutral-gray-900', 'neutral-gray-50'],
  '--semantics-text-link-subtle-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-on-fill-error-default': ['error-red-600', 'error-red-600'],
  '--semantics-text-on-fill-error-focus': ['error-red-600', 'error-red-600'],
  '--semantics-text-on-fill-error-hover': ['error-red-700', 'error-red-700'],
  '--semantics-text-on-fill-error-inversed-dynamic': ['error-red-900', 'error-red-100'],
  '--semantics-text-on-fill-error-inversed-static': ['error-red-900', 'error-red-900'],
  '--semantics-text-on-fill-error-pressed': ['error-red-800', 'error-red-800'],
  '--semantics-text-on-fill-info-default': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-on-fill-info-focus': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-on-fill-info-hover': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-text-on-fill-info-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-text-on-fill-info-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-text-on-fill-info-pressed': ['brand-blue-800', 'brand-blue-800'],
  '--semantics-text-on-fill-subtle-disabled': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-text-on-fill-subtle-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-text-on-fill-subtle-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-text-on-fill-subtle-primary': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-on-fill-subtle-secondary': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-text-on-fill-success-default': ['success-green-600', 'success-green-600'],
  '--semantics-text-on-fill-success-focus': ['success-green-600', 'success-green-600'],
  '--semantics-text-on-fill-success-hover': ['success-green-700', 'success-green-700'],
  '--semantics-text-on-fill-success-inversed-dynamic': ['success-green-900', 'success-green-900'],
  '--semantics-text-on-fill-success-inversed-static': ['success-green-900', 'success-green-100'],
  '--semantics-text-on-fill-success-pressed': ['success-green-800', 'success-green-800'],
  '--semantics-text-on-fill-warning-default': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-text-on-fill-warning-focus': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-text-on-fill-warning-hover': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-text-on-fill-warning-inversed-dynamic': ['warning-orange-900', 'warning-orange-900'],
  '--semantics-text-on-fill-warning-inversed-static': ['warning-orange-900', 'warning-orange-100'],
  '--semantics-text-on-fill-warning-pressed': ['warning-orange-800', 'warning-orange-800'],
  '--semantics-text-status-error-default': ['error-red-500', 'error-red-500'],
  '--semantics-text-status-error-focus': ['error-red-500', 'error-red-500'],
  '--semantics-text-status-error-hover': ['error-red-600', 'error-red-600'],
  '--semantics-text-status-error-inversed-dynamic': ['error-red-900', 'error-red-900'],
  '--semantics-text-status-error-inversed-static': ['error-red-900', 'error-red-100'],
  '--semantics-text-status-error-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-text-status-info-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-status-info-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-text-status-info-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-text-status-info-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-text-status-info-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-text-status-info-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-text-status-subtle-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-status-subtle-focus': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-status-subtle-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-text-status-subtle-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-text-status-subtle-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-text-status-subtle-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-text-status-success-default': ['success-green-500', 'success-green-500'],
  '--semantics-text-status-success-focus': ['success-green-500', 'success-green-500'],
  '--semantics-text-status-success-hover': ['success-green-600', 'success-green-600'],
  '--semantics-text-status-success-inversed-dynamic': ['success-green-900', 'success-green-900'],
  '--semantics-text-status-success-inversed-static': ['success-green-900', 'success-green-100'],
  '--semantics-text-status-success-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-text-status-warning-default': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-text-status-warning-focus': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-text-status-warning-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-text-status-warning-inversed-dynamic': ['warning-orange-900', 'warning-orange-900'],
  '--semantics-text-status-warning-inversed-static': ['warning-orange-900', 'warning-orange-100'],
  '--semantics-text-status-warning-pressed': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-border-subtle-primary': ['neutral-gray-400', 'neutral-gray-400'],
  '--semantics-border-subtle-inversed-dynamic': ['neutral-default', 'neutral-gray-50'],
  '--semantics-border-subtle-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-border-subtle-secondary': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-border-subtle-disabled': ['neutral-gray-400', 'neutral-gray-400'],
  '--semantics-border-brand-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-border-brand-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-border-brand-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-border-brand-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-border-status-error-primary-default': ['error-red-500', 'error-red-500'],
  '--semantics-border-status-error-primary-focus': ['error-red-500', 'error-red-500'],
  '--semantics-border-status-error-primary-hover': ['error-red-600', 'error-red-600'],
  '--semantics-border-status-error-primary-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-border-status-error-secondary-default': ['error-red-100', 'error-red-100'],
  '--semantics-border-status-error-secondary-focus': ['error-red-500', 'error-red-500'],
  '--semantics-border-status-error-secondary-hover': ['error-red-200', 'error-red-200'],
  '--semantics-border-status-error-secondary-pressed': ['error-red-300', 'error-red-300'],
  '--semantics-border-status-info-primary-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-border-status-info-primary-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-border-status-info-primary-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-border-status-info-primary-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-border-status-info-secondary-default': ['brand-blue-100', 'brand-blue-100'],
  '--semantics-border-status-info-secondary-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-border-status-info-secondary-hover': ['brand-blue-200', 'brand-blue-200'],
  '--semantics-border-status-info-secondary-pressed': ['brand-blue-300', 'brand-blue-300'],
  '--semantics-border-status-success-primary-default': ['success-green-500', 'success-green-500'],
  '--semantics-border-status-success-primary-focus': ['success-green-500', 'success-green-500'],
  '--semantics-border-status-success-primary-hover': ['success-green-600', 'success-green-600'],
  '--semantics-border-status-success-primary-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-border-status-success-secondary-default': ['success-green-100', 'success-green-100'],
  '--semantics-border-status-success-secondary-focus': ['success-green-500', 'success-green-500'],
  '--semantics-border-status-success-secondary-hover': ['success-green-200', 'success-green-200'],
  '--semantics-border-status-success-secondary-pressed': ['success-green-300', 'success-green-300'],
  '--semantics-border-status-warning-primary-default': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-border-status-warning-primary-focus': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-border-status-warning-primary-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-border-status-warning-primary-pressed': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-border-status-warning-secondary-default': [
    'warning-orange-100',
    'warning-orange-100',
  ],
  '--semantics-border-status-warning-secondary-focus': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-border-status-warning-secondary-hover': ['warning-orange-200', 'warning-orange-200'],
  '--semantics-border-status-warning-secondary-pressed': [
    'warning-orange-300',
    'warning-orange-300',
  ],
  '--semantics-surface-subtle-primary-default': ['neutral-default', 'neutral-gray-50'],
  '--semantics-surface-subtle-primary-disabled': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-surface-subtle-primary-focus': ['neutral-default', 'neutral-gray-50'],
  '--semantics-surface-subtle-primary-hover': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-surface-subtle-primary-inversed-dynamic': ['neutral-inversed', 'neutral-inversed'],
  '--semantics-surface-subtle-primary-inversed-static': ['neutral-inversed', 'neutral-default'],
  '--semantics-surface-subtle-primary-pressed': ['neutral-gray-100', 'neutral-gray-50'],
  '--semantics-surface-subtle-secondary-default': ['neutral-gray-50', 'neutral-gray-100'],
  '--semantics-surface-subtle-secondary-hover': ['neutral-gray-100', 'neutral-gray-200'],
  '--semantics-surface-subtle-secondary-inversed-dynamic': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-surface-subtle-secondary-inversed-static': ['neutral-gray-900', 'neutral-gray-50'],
  '--semantics-surface-subtle-secondary-pressed': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-surface-subtle-tertiary-default': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-surface-subtle-tertiary-hover': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-surface-subtle-tertiary-pressed': ['neutral-gray-300', 'neutral-gray-200'],
  '--semantics-surface-brand-default': ['brand-blue-500-10', 'brand-blue-500-10'],
  '--semantics-surface-brand-hover': ['brand-blue-500-15', 'brand-blue-500-15'],
  '--semantics-surface-brand-pressed': ['brand-blue-500-10', 'brand-blue-500-10'],
  '--semantics-surface-status-error-primary-default': ['error-red-500', 'error-red-500'],
  '--semantics-surface-status-error-primary-hover': ['error-red-600', 'error-red-600'],
  '--semantics-surface-status-error-primary-inversed-dynamic': ['error-red-900', 'error-red-900'],
  '--semantics-surface-status-error-primary-inversed-static': ['error-red-900', 'error-red-100'],
  '--semantics-surface-status-error-primary-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-surface-status-error-secondary-default': ['error-red-500-10', 'error-red-500-10'],
  '--semantics-surface-status-error-secondary-hover': ['error-red-500-15', 'error-red-500-15'],
  '--semantics-surface-status-error-secondary-pressed': ['error-red-500-25', 'error-red-500-25'],
  '--semantics-surface-status-info-primary-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-surface-status-info-primary-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-surface-status-info-primary-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-surface-status-info-primary-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-surface-status-info-primary-pressed': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-surface-status-info-secondary-default': ['brand-blue-500-10', 'brand-blue-500-10'],
  '--semantics-surface-status-info-secondary-hover': ['brand-blue-500-15', 'brand-blue-500-15'],
  '--semantics-surface-status-info-secondary-pressed': ['brand-blue-500-25', 'brand-blue-500-25'],
  '--semantics-surface-status-subtle-primary-default': ['neutral-inversed', 'neutral-inversed'],
  '--semantics-surface-status-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-surface-status-subtle-primary-inversed-dynamic': [
    'neutral-default',
    'neutral-default',
  ],
  '--semantics-surface-status-subtle-primary-inversed-static': [
    'neutral-default',
    'neutral-inversed',
  ],
  '--semantics-surface-status-subtle-primary-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-surface-status-subtle-secondary-default': [
    'neutral-black-shade-5',
    'neutral-black-shade-5',
  ],
  '--semantics-surface-status-subtle-secondary-hover': [
    'neutral-black-shade-15',
    'neutral-black-shade-15',
  ],
  '--semantics-surface-status-subtle-secondary-inversed-dynamic': [
    'neutral-50-tint-5',
    'neutral-50-tint-5',
  ],
  '--semantics-surface-status-subtle-secondary-pressed': [
    'neutral-black-shade-25',
    'neutral-black-shade-25',
  ],
  '--semantics-surface-status-success-primary-default': ['success-green-500', 'success-green-500'],
  '--semantics-surface-status-success-primary-hover': ['success-green-600', 'success-green-600'],
  '--semantics-surface-status-success-primary-inversed-dynamic': [
    'success-green-900',
    'success-green-900',
  ],
  '--semantics-surface-status-success-primary-inversed-static': [
    'success-green-900',
    'success-green-100',
  ],
  '--semantics-surface-status-success-primary-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-surface-status-success-secondary-default': [
    'success-green-500-10',
    'success-green-500-10',
  ],
  '--semantics-surface-status-success-secondary-hover': [
    'success-green-500-15',
    'success-green-500-15',
  ],
  '--semantics-surface-status-success-secondary-pressed': [
    'success-green-500-25',
    'success-green-500-25',
  ],
  '--semantics-surface-status-warning-primary-default': [
    'warning-orange-500',
    'warning-orange-500',
  ],
  '--semantics-surface-status-warning-primary-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-surface-status-warning-primary-inversed-dynamic': [
    'warning-orange-900',
    'warning-orange-900',
  ],
  '--semantics-surface-status-warning-primary-inversed-static': [
    'warning-orange-900',
    'warning-orange-100',
  ],
  '--semantics-surface-status-warning-primary-pressed': [
    'warning-orange-700',
    'warning-orange-700',
  ],
  '--semantics-surface-status-warning-secondary-default': [
    'warning-orange-500-10',
    'warning-orange-500-10',
  ],
  '--semantics-surface-status-warning-secondary-hover': [
    'warning-orange-500-15',
    'warning-orange-500-15',
  ],
  '--semantics-surface-status-warning-secondary-pressed': [
    'warning-orange-500-25',
    'warning-orange-500-25',
  ],
  '--semantics-icon-subtle-primary-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-subtle-primary-disabled': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-icon-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-icon-subtle-primary-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-icon-subtle-primary-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-icon-subtle-primary-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-subtle-secondary-default': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-icon-subtle-secondary-hover': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-icon-subtle-secondary-inversed-dynamic': ['neutral-gray-50', 'neutral-gray-50'],
  '--semantics-icon-subtle-secondary-inversed-static': ['neutral-gray-50', 'neutral-gray-900'],
  '--semantics-icon-subtle-secondary-pressed': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-icon-brand-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-icon-brand-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-icon-brand-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-icon-brand-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-icon-brand-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-icon-brand-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-icon-on-fill-error-default': ['error-red-600', 'error-red-600'],
  '--semantics-icon-on-fill-error-focus': ['error-red-600', 'error-red-600'],
  '--semantics-icon-on-fill-error-hover': ['error-red-700', 'error-red-700'],
  '--semantics-icon-on-fill-error-inversed-dynamic': ['error-red-900', 'error-red-900'],
  '--semantics-icon-on-fill-error-inversed-static': ['error-red-900', 'error-red-100'],
  '--semantics-icon-on-fill-error-pressed': ['error-red-800', 'error-red-800'],
  '--semantics-icon-on-fill-info-default': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-icon-on-fill-info-focus': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-icon-on-fill-info-hover': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-icon-on-fill-info-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-icon-on-fill-info-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-icon-on-fill-info-pressed': ['brand-blue-800', 'brand-blue-800'],
  '--semantics-icon-on-fill-subtle-disabled': ['neutral-gray-700', 'neutral-gray-700'],
  '--semantics-icon-on-fill-subtle-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-icon-on-fill-subtle-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-icon-on-fill-subtle-primary': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-on-fill-subtle-secondary': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-icon-on-fill-success-default': ['success-green-600', 'success-green-600'],
  '--semantics-icon-on-fill-success-focus': ['success-green-600', 'success-green-600'],
  '--semantics-icon-on-fill-success-hover': ['success-green-700', 'success-green-700'],
  '--semantics-icon-on-fill-success-inversed-dynamic': ['success-green-900', 'success-green-900'],
  '--semantics-icon-on-fill-success-inversed-static': ['success-green-900', 'success-green-100'],
  '--semantics-icon-on-fill-success-pressed': ['success-green-800', 'success-green-800'],
  '--semantics-icon-on-fill-warning-default': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-icon-on-fill-warning-focus': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-icon-on-fill-warning-hover': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-icon-on-fill-warning-inversed-dynamic': ['warning-orange-900', 'warning-orange-900'],
  '--semantics-icon-on-fill-warning-inversed-static': ['warning-orange-900', 'warning-orange-100'],
  '--semantics-icon-on-fill-warning-pressed': ['warning-orange-800', 'warning-orange-800'],
  '--semantics-icon-status-error-primary-default': ['error-red-500', 'error-red-500'],
  '--semantics-icon-status-error-primary-focus': ['error-red-500', 'error-red-500'],
  '--semantics-icon-status-error-primary-hover': ['error-red-600', 'error-red-600'],
  '--semantics-icon-status-error-primary-inversed-dynamic': ['error-red-900', 'error-red-900'],
  '--semantics-icon-status-error-primary-inversed-static': ['error-red-900', 'error-red-100'],
  '--semantics-icon-status-error-primary-pressed': ['error-red-700', 'error-red-700'],
  '--semantics-icon-status-error-secondary-default': ['error-red-500-50', 'error-red-500-75'],
  '--semantics-icon-status-error-secondary-focus': ['error-red-500-50', 'error-red-500-75'],
  '--semantics-icon-status-error-secondary-hover': ['error-red-500-75', 'error-red-500'],
  '--semantics-icon-status-error-secondary-pressed': ['error-red-500', 'error-red-600'],
  '--semantics-icon-status-info-primary-default': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-icon-status-info-primary-focus': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-icon-status-info-primary-hover': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-icon-status-info-primary-inversed-dynamic': ['brand-blue-900', 'brand-blue-900'],
  '--semantics-icon-status-info-primary-inversed-static': ['brand-blue-900', 'brand-blue-100'],
  '--semantics-icon-status-info-primary-pressed': ['brand-blue-700', 'brand-blue-700'],
  '--semantics-icon-status-info-secondary-default': ['brand-blue-500-50', 'brand-blue-500-75'],
  '--semantics-icon-status-info-secondary-focus': ['brand-blue-500-50', 'brand-blue-500-75'],
  '--semantics-icon-status-info-secondary-hover': ['brand-blue-500-75', 'brand-blue-500'],
  '--semantics-icon-status-info-secondary-pressed': ['brand-blue-500', 'brand-blue-600'],
  '--semantics-icon-status-subtle-primary-default': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-status-subtle-primary-hover': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-icon-status-subtle-primary-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-icon-status-subtle-primary-inversed-static': ['neutral-default', 'neutral-inversed'],
  '--semantics-icon-status-subtle-primary-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-status-subtle-secondary-default': [
    'neutral-black-shade-50',
    'neutral-black-shade-50',
  ],
  '--semantics-icon-status-subtle-secondary-focus': [
    'neutral-black-shade-50',
    'neutral-black-shade-50',
  ],
  '--semantics-icon-status-subtle-secondary-hover': [
    'neutral-black-shade-75',
    'neutral-black-shade-75',
  ],
  '--semantics-icon-status-subtle-secondary-pressed': ['neutral-gray-900', 'neutral-gray-900'],
  '--semantics-icon-status-success-primary-default': ['success-green-500', 'success-green-500'],
  '--semantics-icon-status-success-primary-focus': ['success-green-500', 'success-green-500'],
  '--semantics-icon-status-success-primary-hover': ['success-green-600', 'success-green-600'],
  '--semantics-icon-status-success-primary-inversed-dynamic': [
    'success-green-900',
    'success-green-900',
  ],
  '--semantics-icon-status-success-primary-inversed-static': [
    'success-green-900',
    'success-green-100',
  ],
  '--semantics-icon-status-success-primary-pressed': ['success-green-700', 'success-green-700'],
  '--semantics-icon-status-success-secondary-default': [
    'success-green-500-50',
    'success-green-500-75',
  ],
  '--semantics-icon-status-success-secondary-focus': [
    'success-green-500-50',
    'success-green-500-75',
  ],
  '--semantics-icon-status-success-secondary-hover': ['success-green-500-75', 'success-green-500'],
  '--semantics-icon-status-success-secondary-pressed': ['success-green-500', 'success-green-600'],
  '--semantics-icon-status-warning-primary-default': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-icon-status-warning-primary-focus': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-icon-status-warning-primary-hover': ['warning-orange-600', 'warning-orange-600'],
  '--semantics-icon-status-warning-primary-inversed-dynamic': [
    'warning-orange-900',
    'warning-orange-900',
  ],
  '--semantics-icon-status-warning-primary-inversed-static': [
    'warning-orange-900',
    'warning-orange-100',
  ],
  '--semantics-icon-status-warning-primary-pressed': ['warning-orange-700', 'warning-orange-700'],
  '--semantics-icon-status-warning-secondary-default': [
    'warning-orange-500-50',
    'warning-orange-500-75',
  ],
  '--semantics-icon-status-warning-secondary-focus': [
    'warning-orange-500-50',
    'warning-orange-500-75',
  ],
  '--semantics-icon-status-warning-secondary-hover': [
    'warning-orange-500-75',
    'warning-orange-500',
  ],
  '--semantics-icon-status-warning-secondary-pressed': ['warning-orange-500', 'warning-orange-600'],
  '--semantics-avatar-one': ['brand-blue-500', 'brand-blue-500'],
  '--semantics-avatar-two': ['warning-orange-500', 'warning-orange-500'],
  '--semantics-avatar-three': ['error-red-500', 'error-red-500'],
  '--semantics-avatar-four': ['success-green-500', 'success-green-500'],
  '--semantics-avatar-five': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-avatar-six': ['neutral-gray-100', 'neutral-gray-100'],
  '--semantics-avatar-seven': ['neutral-gray-200', 'neutral-gray-200'],
  '--semantics-code-comment': ['neutral-gray-800', 'neutral-gray-800'],
  '--semantics-code-function': ['brand-blue-600', 'brand-blue-600'],
  '--semantics-code-inversed-dynamic': ['neutral-default', 'neutral-default'],
  '--semantics-code-keyword': ['utilities-purple-600', 'utilities-purple-600'],
  '--semantics-code-overlay': ['neutral-black-shade-2', 'neutral-black-shade-2'],
  '--semantics-code-properties': ['error-red-500', 'error-red-500'],
  '--semantics-code-string': ['utilities-lime-700', 'utilities-lime-700'],
  '--semantics-code-text': ['neutral-inversed', 'neutral-inversed'],
  '--semantics-sidebar-default': ['neutral-gray-50', 'neutral-default'],
  '--semantics-sidebar-hover': ['neutral-gray-100', 'neutral-gray-200'],
  '--semantics-sidebar-collapsed-hover': ['neutral-gray-50', 'neutral-gray-200'],
  '--semantics-sidebar-collapsed-pressed': ['neutral-gray-50', 'neutral-gray-200'],
  '--semantics-sidebar-expanded-hover': ['neutral-gray-100', 'neutral-gray-200'],
  '--semantics-sidebar-expanded-pressed': ['neutral-default', 'neutral-gray-900'],
};
